splitio/split-evaluator

Dockerfile, README.md, docker-compose.yml, package.json, sdk.js, server.js
TO run the container open the terminal and type: 
```
docker run -e EXT_API_KEY=${SPLITIO_EXT_API_KEY} -e API_KEY=${SPLITIO_API_KEY} -p ${SPLITIO_PORT}:7548 splitsoftware/callhome:1.0
```
=> Fixed dockerfile command and env

server.js
* version & documentation updates will be done in a few after checking with the team, but I want to give the endpoint to QA.
=> Adding /machine endpoint

CHANGES.txt, app.js, client/__tests__/track.test.js, client/__tests__/treatment.test.js, client/__tests__/treatmentWithConfig.test.js, client/__tests__/treatments.test.js, client/__tests__/treatmentsWithConfig.test.js, client/client.router.js, manager/__tests__/split.test.js, manager/__tests__/splitNames.test.js, manager/__tests__/splits.test.js, manager/manager.controller.js, manager/manager.router.js, package-lock.json, package.json, utils/utils.js
* [SDKS-936: Add Manager API](https://splitio.atlassian.net/browse/SDKS-936)
* Added `manager` API.
* Added tests.
=> [SDKS-936]: Add Manager

CHANGES.txt, README.md, package-lock.json, package.json, sdk.js
* [SDKS-1014: File evaluator version for impressions](https://splitio.atlassian.net/browse/SDKS-1014)
* Added version to be populated for tracking evaluator.
* Updated `package.json` to point to nodejs stable version.
* Updated `README.md` and `CHANGES`.
=> [SDKS-1014]: File evaluator version for impressions

openapi/openapi.yaml
correct swagger example typo for get-all-treatments
* Running the docker container locally
=> add square bracket to swagger

.github/pull_request_template.md, CONTRIBUTORS-GUIDE.md, README.md
* Final updates on documentation
=> updated documentation

Dockerfile
* Reduced size of the final Docker image.
* Reduced vulnerabilities.
docker build -t split-evaluator .
=> Switchted to alpine and added multi-stage

.travis.yml
* Run docker build on Travis to verify that it's working.
Check Travis
Automate docker push to Artifactory/Xray.
Automate docker push to Dockerhub.
=> Added docker build to travis

.travis.yml
Docker build & push into Artifactory when the branch is development or master.
A cron job with the same will be run once a day.
Check Travis status.
=> Push Docker image to Artifactory

package-lock.json, package.json
=> release version

package-lock.json, package.json
Updating dependencies to fix vulnerabilities and take advantage of newer features.
Run the tests, check the builds, run the app.
=> Deps update

CHANGES.txt, package-lock.json, package.json
=> Update js 10.15.4

.github/workflows/ci.yml, CHANGES.txt, Dockerfile, openapi/openapi.yaml, package-lock.json, package.json
=> Jfrog scan updates

admin/__tests__/healthcheck.test.js, admin/__tests__/version.test.js, admin/admin.controller.js, environmentManager/index.js, jest.config.js, listener/__tests__/ip-addresses.test.js, listener/index.js, listener/manager.js
[MES] fix and update unit tests to work with environmentManager approach
=> [MES] fix and update unit tests to work with environmentManager approach

.jest/setEnvVars.js, client/__tests__/treatment.test.js, environmentManager/__tests__/environmentManager.test.js, environmentManager/index.js, listener/__tests__/ip-addresses.test.js, listener/__tests__/listener.test.js, listener/index.js, listener/manager.js, package.json
Added tests to environment manager.
In those tests we ensure that each `getTreatment` call is made with the related `api key` for each `authToken`
=> Environment manager tests

environmentManager/__tests__/client.test.js, environmentManager/__tests__/manager.test.js, manager/manager.controller.js
Added tests for manager endpoints (split, splits, names) and track endpoint
=> [SDKS-6160] add tests to environmentManager for manager endpoints and track

environmentManager/index.js, package.json
Log when client is ready and when client timed out ready
=> [SDKS-6255] Log client readiness

CHANGES.txt, listener/manager.js, package-lock.json, package.json
=> Prepare release v2.2.0

CHANGES.txt, package-lock.json, package.json
Update changefile and prepare rc
=> update changefile and rc version

package-lock.json, package.json
=> Bump json5

package-lock.json, package.json
=> update config version

.github/workflows/cd.yml, .github/workflows/unstable.yml, package-lock.json, package.json
Bump config and update docker-login in ci
=> Bump config and update docker-login in ci

.github/workflows/ci.yml, CHANGES.txt, Dockerfile, package-lock.json, package.json
=> Update split sdk & fix vulnerabilities

manager/__tests__/split.test.js, manager/manager.controller.js, manager/manager.router.js
=> [SDKS-6932][DW] Update manager controller and router

utils/testWrapper/index.js
=> [SDKS-6933][DW] Update variables in testWrapper

client/client.controller.js, client/client.router.js, client/common.js
=> [SDKS-6934][DW] Update client controller, router & common

README.md, environmentManager/__tests__/manager.test.js, manager/__tests__/splitNames.test.js, manager/__tests__/splits.test.js, openapi/openapi.yaml, utils/inputValidation/__tests__/splits.test.js, utils/inputValidation/splits.js
=> [SDKS-6958][DW] Replace splits, splitName, web console and apikey

CHANGES.txt, package-lock.json, package.json
=> v2.3.2-rc.0

README.md, package-lock.json, package.json
=> v2.3.2 release

.github/workflows/ci.yml, Dockerfile, package-lock.json, package.json
- Update node version to `18.16`
- Update alpine version to `18.16.0-alpine3.18`
- Update npm version to `9.8.0`
- Update splitio version to `10.22.7-rc.0`
-
=> Release v2.4.0

.jest/setEnvVars.js, environmentManager/__tests__/globalConfig.test.js, environmentManager/__tests__/validation.test.js, environmentManager/index.js, package-lock.json, package.json, utils/inputValidation/flagSet.js, utils/mocks/index.js, utils/parserConfigs/index.js, utils/split3.yml, utils/split4.yml
- tests for flag sets config
- improvements on validations
=> [SDKS-7653] Improvements & tests

client/__tests__/treatmentsByFlagSets.test.js, client/__tests__/treatmentsWithConfigByFlagSets.test.js, client/client.router.js, openapi/openapi.yaml, utils/constants.js, utils/inputValidation/flagSet.js
=> Rename query param from set-names to flag-sets

CHANGES.txt
=> Fix conflict

CHANGES.txt
=> Fix release date in changes file

CHANGES.txt, Dockerfile
=> Prepare release
